BaseURL = "https://www.arresteddevops.com/"
# BaseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Arrested DevOps"
theme = "castanet"
canonifyurls = false
buildFuture = false
buildDrafts = false
dataDir = "data"
disqusShortname = "arresteddevops"
archetypedir = "archetypes"
paginate = 9
googleAnalytics = "UA-45939822-1"

[permalinks]
	page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"
	sponsor = "/:filename"
	redirect = "/:filename"

# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier
 [[Menu.Main]]
     name = "About"
     identifier = "about"
     url = "about"
 [[Menu.Main]]
    name = "Contact"
    identifier = "contact"
    url = "contact"
 [[Menu.Main]]
    name = "Guests"
    identifier = "guests"
    url = "guest"
 [[Menu.Main]]
    name = "Resources"
    identifier = "resources"
    url = "#!"
 [[Menu.Main]]
    name = "Books"
    identifier = "books"
    url = "books"
    parent = "resources"
[[Menu.Main]]
    name = "Blogs"
    identifier = "blogs"
    url = "blogs"
    parent = "resources"
    
[[Menu.Main]]
    name = "Podcasts"
    identifier = "podcasts"
    url = "podcasts"
    parent = "resources"
[[Menu.Main]]
    name = "Sponsor Arrested DevOps"
    identifier = "sponsor"
    url = "sponsorship"

[params]
mainSections = ["episode"]
site_theme = "grey"
site_layout = "grid"
enable_jumbo = "false"
favicon = "favicon.ico"
copyright_notice = "Copyright 2013-2019 [Arrested DevOps](https://www.arresteddevops.com)"
spotify_subscribe = "https://open.spotify.com/show/7hHA2ZlfOmbwv96wEBaMR2?si=UeVjoWIVSqqLluJd4TlEUg"
itunes_subscribe = "http://itunes.apple.com/us/podcast/arrested-devops/id773888088?mt=2&uo=4&at=11lsCi"
android_subscribe = "http://subscribeonandroid.com/www.arresteddevops.com/episode/index.xml"
google_play_subscribe = "https://play.google.com/music/m/Ihj4yege3lfmp3vs5yoopgxijpi?t%3DArrested_DevOps"
stitcher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
pocketcasts_subscribe = "https://pca.st/VqEP"
mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "Arrested DevOps is the podcast that helps you achieve understanding, develop good practices, and operate your team and organization for maximum DevOps awesomeness."
media_prefix = "https://media.blubrry.com/arresteddevops/content.blubrry.com/arresteddevops/"
  [params.feed]
    feed_copyright = "Copyright 2013-2019 Arrested DevOps" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "There's always DevOps in the Banana Stand" #no markdown or HTML
    itunes_author = "Matty Stratton, Trevor Hess, Jessica Kerr, and Bridget Kromhout" #no markdown or HTML
    itunes_summary = "Arrested DevOps is the podcast that helps you achieve understanding, develop good practices, and operate your team and organization for maximum DevOps awesomeness." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Matt Stratton"
    itunes_owner_email = "matt.stratton@gmail.com" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "https://www.arresteddevops.com/img/ado-podcast-logo.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Software How-To"
    itunes_second_sub_category = "Tech News"

  [params.social]
    github = "arresteddevops"
    facebook = "Arresteddevops"
    facebook_admin = ["500557137"]  # This needs to be a page admin to get domain insights
    twitter = "arresteddevops"
    twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    instagram = "arresteddevops"
    youtube = "arresteddevops"

  [params.authors]
    [params.authors.Ado]
		name = ""
		thumbnail = "img/ado-logo-150.png"
		bio = ""

